{"uid":"eb0e436f4c2f03fc","name":"测试登录","fullName":"testcase.test_Login#test_login","historyId":"e74e289d6115a7155493cea255fe26cd","time":{"start":1695390763273,"stop":1695390763540,"duration":267},"description":"执行测试登录的结果是test","descriptionHtml":"<p>执行测试登录的结果是test</p>\n","status":"broken","statusMessage":"AttributeError: 'AssertUtil' object has no attribute 'log'","statusTrace":"self = <utils.AssertUtil.AssertUtil object at 0x10469b9a0>\nbody = '{\"success\": false, \"code\": 20001, \"message\": \"\\\\u7528\\\\u6237\\\\u540d\\\\u6216\\\\u5bc6\\\\u7801\\\\u9519\\\\u8bef\", \"data\": null}'\nexpected_body = '\"success\": true'\n\n    def assert_in_body(self, body, expected_body):\n        \"\"\"\n        验证返回结果是否包含期望结果\n        :param body:\n        :param expected_body:\n        :return:\n        \"\"\"\n        try:\n            body = json.dumps(body)\n>           assert expected_body in body\nE           AssertionError\n\n../utils/AssertUtil.py:52: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\n    @allure.title(\"测试登录\")\n    @allure.description(\"执行测试登录的结果是test\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_login():\n        # 3、定义测试数据\n        conf_y = ConfigYaml()\n        url_path = conf_y.get_conf_url()\n        url = url_path + \"/sys/login\"\n        # url = \"http://ihrm-java.itheima.net/api/sys/login\"\n        data = {\"mobile\": \"13800000002\", \"password\": \"888itcast.CN764%.\"}\n        headers = {\"Content-Type\": \"application/json\"}\n        # 4、发送POST请求\n        # r = requests.post(url, json=data, headers=headers)\n        # r = requests_post(url, json=data, headers=headers)\n        request = Request()\n        r = request.post(url, json=data, headers=headers)\n        # 5、输出结果\n        # print(r.json())\n        print(r)\n        # 验证\n        # 返回状态码\n        code = r[\"code\"]\n        AssertUtil().assert_code(code, 200)\n        # 返回body\n        # body = json.dumps(r[\"body\"])\n        # assert '\"success\": true,\"data\": \"9829dd98-6dcc-41e1-901d-4e434cde36d6\"' in body\n        body = r[\"body\"]\n>       AssertUtil().assert_in_body(body, '\"success\": true')\n\ntest_Login.py:48: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utils.AssertUtil.AssertUtil object at 0x10469b9a0>\nbody = '{\"success\": false, \"code\": 20001, \"message\": \"\\\\u7528\\\\u6237\\\\u540d\\\\u6216\\\\u5bc6\\\\u7801\\\\u9519\\\\u8bef\", \"data\": null}'\nexpected_body = '\"success\": true'\n\n    def assert_in_body(self, body, expected_body):\n        \"\"\"\n        验证返回结果是否包含期望结果\n        :param body:\n        :param expected_body:\n        :return:\n        \"\"\"\n        try:\n            body = json.dumps(body)\n            assert expected_body in body\n            return True\n        except:\n>           self.log.error(\"不包含或者body错误,body is %s,expected_body is %s\" % (body, expected_body))\nE           AttributeError: 'AssertUtil' object has no attribute 'log'\n\n../utils/AssertUtil.py:55: AttributeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":3,"retriesStatusChange":false,"beforeStages":[],"testStage":{"description":"执行测试登录的结果是test","status":"broken","statusMessage":"AttributeError: 'AssertUtil' object has no attribute 'log'","statusTrace":"self = <utils.AssertUtil.AssertUtil object at 0x10469b9a0>\nbody = '{\"success\": false, \"code\": 20001, \"message\": \"\\\\u7528\\\\u6237\\\\u540d\\\\u6216\\\\u5bc6\\\\u7801\\\\u9519\\\\u8bef\", \"data\": null}'\nexpected_body = '\"success\": true'\n\n    def assert_in_body(self, body, expected_body):\n        \"\"\"\n        验证返回结果是否包含期望结果\n        :param body:\n        :param expected_body:\n        :return:\n        \"\"\"\n        try:\n            body = json.dumps(body)\n>           assert expected_body in body\nE           AssertionError\n\n../utils/AssertUtil.py:52: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\n    @allure.title(\"测试登录\")\n    @allure.description(\"执行测试登录的结果是test\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_login():\n        # 3、定义测试数据\n        conf_y = ConfigYaml()\n        url_path = conf_y.get_conf_url()\n        url = url_path + \"/sys/login\"\n        # url = \"http://ihrm-java.itheima.net/api/sys/login\"\n        data = {\"mobile\": \"13800000002\", \"password\": \"888itcast.CN764%.\"}\n        headers = {\"Content-Type\": \"application/json\"}\n        # 4、发送POST请求\n        # r = requests.post(url, json=data, headers=headers)\n        # r = requests_post(url, json=data, headers=headers)\n        request = Request()\n        r = request.post(url, json=data, headers=headers)\n        # 5、输出结果\n        # print(r.json())\n        print(r)\n        # 验证\n        # 返回状态码\n        code = r[\"code\"]\n        AssertUtil().assert_code(code, 200)\n        # 返回body\n        # body = json.dumps(r[\"body\"])\n        # assert '\"success\": true,\"data\": \"9829dd98-6dcc-41e1-901d-4e434cde36d6\"' in body\n        body = r[\"body\"]\n>       AssertUtil().assert_in_body(body, '\"success\": true')\n\ntest_Login.py:48: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utils.AssertUtil.AssertUtil object at 0x10469b9a0>\nbody = '{\"success\": false, \"code\": 20001, \"message\": \"\\\\u7528\\\\u6237\\\\u540d\\\\u6216\\\\u5bc6\\\\u7801\\\\u9519\\\\u8bef\", \"data\": null}'\nexpected_body = '\"success\": true'\n\n    def assert_in_body(self, body, expected_body):\n        \"\"\"\n        验证返回结果是否包含期望结果\n        :param body:\n        :param expected_body:\n        :return:\n        \"\"\"\n        try:\n            body = json.dumps(body)\n            assert expected_body in body\n            return True\n        except:\n>           self.log.error(\"不包含或者body错误,body is %s,expected_body is %s\" % (body, expected_body))\nE           AttributeError: 'AssertUtil' object has no attribute 'log'\n\n../utils/AssertUtil.py:55: AttributeError","steps":[],"attachments":[{"uid":"b0c797961c4fa05f","name":"log","source":"b0c797961c4fa05f.txt","type":"text/plain","size":215}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true},"afterStages":[],"labels":[{"name":"severity","value":"critical"},{"name":"parentSuite","value":"testcase"},{"name":"suite","value":"test_Login"},{"name":"host","value":"lifaliangdeMacBook-Air.local"},{"name":"thread","value":"33748-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"testcase.test_Login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[{"uid":"104cc6c03fb14546","status":"broken","statusDetails":"AttributeError: 'AssertUtil' object has no attribute 'log'","time":{"start":1695390761128,"stop":1695390761263,"duration":135}},{"uid":"e0488db8ad77dd6d","status":"broken","statusDetails":"AttributeError: 'AssertUtil' object has no attribute 'log'","time":{"start":1695390758982,"stop":1695390759109,"duration":127}},{"uid":"963b1578e640bcf5","status":"broken","statusDetails":"AttributeError: 'AssertUtil' object has no attribute 'log'","time":{"start":1695390756648,"stop":1695390756925,"duration":277}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"eb0e436f4c2f03fc.json","parameterValues":[]}